default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>

development:
  <<: *default
  database: <%= ENV.fetch 'POSTGRES_DB', 'redmine_development' %>

test:
  <<: *default
  database: <%= ENV.fetch 'POSTGRES_DB', 'redmine_test' %>

production:
  <<: *default
  database: <%= ENV.fetch 'POSTGRES_DB', 'redmine' %>

